### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by DrCSLin** [projectceladon/manifest#182]
Dears,
I built the CiC and I met the build fail.
I use the repo init command "repo init -u https://github.com/projectceladon/manifest -b **celadon/p/mr0/master** -m cic"
And I found the the out folder did not contain the file "out/target/product/cic/**verity_metadata**" . 
please give some hints.
many thanks

Here is the build log:
[ 99% 25329/25331] Install system fs image: out/target/product/cic/system.img
WARNING: out/target/product/cic/system.img+ approaching size limit (2147483648 now; limit 2147483648)
[ 99% 25330/25331] Make multidroid image...
FAILED: multidroid 
/bin/bash -c "(rm -rf out/target/product/cic/docker ) && (mkdir -p out/target/product/cic/docker/android/root ) && (cp -r ./vendor/intel/cic/host/docker/aic-manager out/target/product/cic/docker ) && (mkdir -p out/target/product/cic/docker/aic-manager/data/ashmem ) && (cp -r ./kernel/modules/cic/ashmem/* out/target/product/cic/docker/aic-manager/data/ashmem/ ) && (mkdir -p out/target/product/cic/docker/aic-manager/data/binder ) && (cp -r ./kernel/modules/cic/binder/* out/target/product/cic/docker/aic-manager/data/binder/ ) && (cp -r ./vendor/intel/cic/host/docker/android out/target/product/cic/docker ) && (cp -r ./vendor/intel/cic/host/docker/update out/target/product/cic/docker ) && (cp ./vendor/intel/cic/host/docker/scripts/aic out/target/product/cic ) && (cp -r out/target/product/cic/efi/kf4cic.efi out/target/product/cic/kf4cic.efi ) && (zcat out/target/product/cic/ramdisk.img | (cd out/target/product/cic/docker/android/root && cpio -idm) ) && (rm -rf out/target/product/cic/docker/android/root/etc ) && (cp -r out/target/product/cic/system/etc out/target/product/cic/docker/android/root ) && (rm -rf out/target/product/cic/docker/aic-manager/images ) && (mkdir -p out/target/product/cic/docker/aic-manager/images ) && (echo Enter verity_metadata ) && (python out/host/linux-x86/bin/build_verity_img.py out/target/product/cic/system.img out/target/product/cic/verity_metadata )  && (ln -t out/target/product/cic/docker/aic-manager/images out/target/product/cic/system.img )"
8913 blocks
Traceback (most recent call last):
  File "out/host/linux-x86/bin/build_verity_img.py", line 78, in <module>
    main(sys.argv[1:])
  File "out/host/linux-x86/bin/build_verity_img.py", line 74, in main
    if not build_verity_metadata(input_file, output_file):
  File "out/host/linux-x86/bin/build_verity_img.py", line 35, in build_verity_metadata
    output, exit_code = RunCommand(cmd)
  File "out/host/linux-x86/bin/build_verity_img.py", line 25, in RunCommand
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
ninja: build stopped: subcommand failed.
14:12:43 ninja failed with: exit status 1

**Comment by iViggyPrabhu** [comment]
@DrCSLin can you please install cryptsetup-bin package in your system and then try building it.

`sudo apt-get install cryptsetup-bin`

**Comment by DrCSLin** [comment]
@iViggyPrabhu many thanks, it built successfully after installing cryptsetup-bin.
