### ISSUE TITLE
How do build Android-ia Nougat

### ISSUE THREAD

**Issue by iiowoii** [projectceladon/manifest#299]
How do build android-ia nougat，manifest not found nougat xml

**Comment by iiowoii** [comment]
I need it Android Nougat

**Comment by iViggyPrabhu** [comment]
Hi @iiowoii , 

Thanks for connecting with us. Right now, I dont think we support Android Nougat. However, if you can connect with us on [Celadon mailing list](https://lists.linuxfoundation.org/mailman/listinfo/celadon) and explain your usecase, our developers can recommend you the best option for you.
